import React from 'react';

export const Props = {

    /*多屏适配白名单*/
    sizeProps: new Set([
        'width',
        'minWidth',
        'height',
        'minHeight',
        'fontSize',
        'margin',
        'marginTop',
        'marginLeft',
        'marginRight',
        'marginBottom',
        'marginVertical',
        'marginHorizontal',
        'padding',
        'paddingTop',
        'paddingLeft',
        'paddingRight',
        'paddingBottom',
        'paddingVertical',
        'paddingHorizontal',
        'top',
        'left',
        'right',
        'bottom',
        'borderWidth',
        'borderRadius',
        'borderTopTopRadius',
        'borderTopLeftRadius',
        'borderTopRightRadius',
        'borderBottomRightRadius',
    ]),

    /*文本控件属性白名单*/
    textProps: new Set([
        'color',
        'fontFamily',
        'fontSize',
        'fontStyle',
        'fontVariant',
        'fontWeight',
        'includeFontPadding',
        'letterSpacing',
        'lineHeight',
        'textAlign',
        'textAlignVertical',
        'textDecorationColor',
        'textDecorationLine',
        'textDecorationStyle',
        'textShadowColor',
        'textShadowOffset',
        'textShadowRadius',
        'textTransform',
        'writingDirection',
        'textDisabled',
    ]),
};
