export const Props = {

  /* White list of multi-screen adaptation properties */
  sizeProps: new Set([
    'width',
    'minWidth',
    'height',
    'minHeight',
    'fontSize',
    'margin',
    'marginTop',
    'marginLeft',
    'marginRight',
    'marginBottom',
    'marginVertical',
    'marginHorizontal',
    'padding',
    'paddingTop',
    'paddingLeft',
    'paddingRight',
    'paddingBottom',
    'paddingVertical',
    'paddingHorizontal',
    'top',
    'left',
    'right',
    'bottom',
    'borderWidth',
    'borderRadius',
    'borderTopTopRadius',
    'borderTopLeftRadius',
    'borderTopRightRadius',
    'borderBottomRightRadius',
  ]),

  /* Whitelist of text style control properties */
  textStyleProps: new Set([
    'color',
    'fontFamily',
    'fontSize',
    'fontStyle',
    'fontVariant',
    'fontWeight',
    'includeFontPadding',
    'letterSpacing',
    'lineHeight',
    'textAlign',
    'textAlignVertical',
    'textDecorationColor',
    'textDecorationLine',
    'textDecorationStyle',
    'textShadowColor',
    'textShadowOffset',
    'textShadowRadius',
    'textTransform',
    'writingDirection',
    'textDisabled',
  ]),

  /* Whitelist of text control properties */
  textProps: new Set([
    'allowFontScaling',
    'ellipsizeMode',
    'lineBreakMode',
    'numberOfLines',
    'nativeID',
    'maxFontSizeMultiplier',
  ]),
};
